require("dotenv").config();
const express=require("express"),cors=require("cors"),{initSchema}=require("./db");
const app=express();
const origins=process.env.CORS_ORIGIN||"*";
app.use(cors({origin:origins==="*" ? true : origins.split(",").map(x=>x.trim())}));
app.use("/api/webhooks",require("./routes/webhooks"));
app.use(express.json({limit:"2mb"}));
app.get("/health",(req,res)=>res.json({ok:true}));
app.get("/",(req,res)=>res.json({name:"AI Sales Cameroun",ok:true}));
app.use("/api/auth",require("./routes/auth"));
app.use("/api/generate",require("./routes/generate"));
app.use("/api/crm",require("./routes/crm"));
app.use("/api/products",require("./routes/products"));
app.use("/api/faqs",require("./routes/faqs"));
app.use("/api/sequences",require("./routes/sequences"));
app.use("/api/tasks",require("./routes/tasks"));
app.use("/api/analytics",require("./routes/analytics"));
app.use("/api/whatsapp",require("./routes/whatsapp"));
app.use("/api/admin",require("./routes/admin"));
app.use("/api/chariow",require("./routes/chariow"));
const PORT=process.env.PORT||8080;
initSchema().then(()=>app.listen(PORT,()=>console.log(`AI Sales Cameroun backend en écoute sur le port ${PORT}`))).catch(e=>{console.error("Impossible d'initialiser la base de données :",e);process.exit(1);});
module.exports=app;
