const express=require("express"),{requireAuth}=require("../auth"),{pool}=require("../db"),router=express.Router();
async function admin(req,res,next){const r=await pool.query("SELECT is_admin FROM users WHERE id=$1",[req.userId]);if(!r.rows[0]?.is_admin)return res.status(403).json({message:"Accès administrateur refusé."});next();}
router.use(requireAuth,admin);
router.get("/stats",async(req,res)=>{try{const u=await pool.query("SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE suspended)::int suspended,COUNT(*) FILTER(WHERE created_at>=NOW()-INTERVAL '7 days')::int new FROM users"),p=await pool.query("SELECT plan,COUNT(*)::int count FROM users GROUP BY plan"),r=await pool.query("SELECT COALESCE(SUM(CASE WHEN plan='pro' THEN 14900 WHEN plan='business' THEN 39900 ELSE 0 END),0)::int mrr FROM users");const pc={free:0,pro:0,business:0};p.rows.forEach(x=>pc[x.plan]=x.count);res.json({totalUsers:u.rows[0].total,suspendedUsers:u.rows[0].suspended,newUsersThisWeek:u.rows[0].new,planCounts:pc,mrrFcfa:r.rows[0].mrr});}catch(e){res.status(500).json({message:"Erreur serveur."});}});
router.get("/users",async(req,res)=>{try{const page=Math.max(1,Number(req.query.page)||1),size=Math.min(100,Math.max(1,Number(req.query.pageSize)||20)),allowed=["email","plan","created_at","last_login_at"],sort=allowed.includes(req.query.sort)?req.query.sort:"created_at",order=req.query.order==="asc"?"ASC":"DESC",args=[];let w="TRUE";if(req.query.q){args.push(`%${req.query.q}%`);w+=` AND email ILIKE $${args.length}`;}if(["free","pro","business"].includes(req.query.plan)){args.push(req.query.plan);w+=` AND plan=$${args.length}`;}if(req.query.suspended==="true")w+=" AND suspended=true";const total=(await pool.query(`SELECT COUNT(*)::int total FROM users WHERE ${w}`,args)).rows[0].total;args.push(size,(page-1)*size);const rows=(await pool.query(`SELECT id,email,plan,plan_expires_at,suspended,is_admin,last_login_at,created_at FROM users WHERE ${w} ORDER BY ${sort} ${order} LIMIT $${args.length-1} OFFSET $${args.length}`,args)).rows;res.json({users:rows,total,totalPages:Math.max(1,Math.ceil(total/size))});}catch(e){res.status(500).json({message:"Erreur serveur."});}});
router.get("/users/:id",async(req,res)=>{try{const u=(await pool.query("SELECT id,email,plan,plan_expires_at,suspended,is_admin,created_at,last_login_at FROM users WHERE id=$1",[req.params.id])).rows[0];if(!u)return res.status(404).json({message:"Utilisateur introuvable."});const contacts=(await pool.query("SELECT COUNT(*)::int n FROM contacts WHERE user_id=$1",[req.params.id])).rows[0].n,activities=(await pool.query("SELECT COUNT(*)::int n FROM contact_activities a JOIN contacts c ON c.id=a.contact_id WHERE c.user_id=$1",[req.params.id])).rows[0].n,usageHistory=(await pool.query("SELECT period,count FROM usage_monthly WHERE user_id=$1 ORDER BY period DESC LIMIT 12",[req.params.id])).rows,recentAudit=(await pool.query("SELECT action,created_at FROM audit_log WHERE target_user_id=$1 ORDER BY created_at DESC LIMIT 10",[req.params.id])).rows;res.json({user:u,contactsCount:contacts,activitiesCount:activities,usageHistory,recentAudit});}catch(e){res.status(500).json({message:"Erreur serveur."});}});
router.patch("/users/:id",async(req,res)=>{try{const s=[],v=[];let n=1;if(["free","pro","business"].includes(req.body.plan)){s.push(`plan=$${n++}`);v.push(req.body.plan);s.push(`plan_expires_at=$${n++}`);v.push(req.body.plan==="free"?null:new Date(Date.now()+30*86400000));}if(req.body.suspended!==undefined){s.push(`suspended=$${n++}`);v.push(!!req.body.suspended);}if(req.body.isAdmin!==undefined){s.push(`is_admin=$${n++}`);v.push(!!req.body.isAdmin);}if(!s.length)return res.json({ok:true});v.push(req.params.id);const{rows}=await pool.query(`UPDATE users SET ${s.join(",")} WHERE id=$${n} RETURNING *`,v);if(!rows.length)return res.status(404).json({message:"Utilisateur introuvable."});await pool.query("INSERT INTO audit_log(admin_user_id,action,target_user_id,details) VALUES($1,'update_user',$2,$3)",[req.userId,req.params.id,req.body]);res.json({user:rows[0]});}catch(e){res.status(500).json({message:"Erreur serveur."});}});
router.post("/users/:id/reset-usage",async(req,res)=>{try{await pool.query("UPDATE usage_monthly SET count=0 WHERE user_id=$1 AND period=$2",[req.params.id,new Date().toISOString().slice(0,7)]);await pool.query("INSERT INTO audit_log(admin_user_id,action,target_user_id) VALUES($1,'reset_usage',$2)",[req.userId,req.params.id]);res.json({ok:true});}catch(e){res.status(500).json({message:"Erreur serveur."});}});
router.delete("/users/:id",async(req,res)=>{try{if(String(req.params.id)===String(req.userId))return res.status(400).json({message:"Suppression de votre propre compte interdite ici."});await pool.query("DELETE FROM users WHERE id=$1",[req.params.id]);await pool.query("INSERT INTO audit_log(admin_user_id,action,target_user_id) VALUES($1,'delete_user',$2)",[req.userId,req.params.id]);res.json({ok:true});}catch(e){res.status(500).json({message:"Erreur serveur."});}});
router.get("/audit-log",async(req,res)=>{try{const size=Math.min(100,Math.max(1,Number(req.query.pageSize)||30)),page=Math.max(1,Number(req.query.page)||1);const rows=(await pool.query("SELECT al.id,au.email admin_email,al.action,tu.email target_email,al.target_user_id,al.details,al.created_at FROM audit_log al LEFT JOIN users au ON au.id=al.admin_user_id LEFT JOIN users tu ON tu.id=al.target_user_id ORDER BY al.created_at DESC LIMIT $1 OFFSET $2",[size,(page-1)*size])).rows,total=(await pool.query("SELECT COUNT(*)::int n FROM audit_log")).rows[0].n;res.json({entries:rows,totalPages:Math.max(1,Math.ceil(total/size))});}catch(e){res.status(500).json({message:"Erreur serveur."});}});
module.exports=router;
