const express=require("express"),Anthropic=require("@anthropic-ai/sdk"),{requireAuth}=require("../auth"),{getUser,consumeGeneration}=require("../plan"),{pool}=require("../db");
const router=express.Router();
const PLATFORMS=["facebook","instagram","tiktok","x","whatsapp"];
const OBJECTIVES=["sales","leads","whatsapp_messages","traffic","awareness"];
router.use(requireAuth);
router.get("/status",async(req,res)=>{try{const u=await getUser(req.userId);if(!u||u.plan!=="business")return res.status(403).json({message:"Publicité IA est réservée au plan Business.",code:"business_required"});const {rows}=await pool.query("SELECT id,name,platform,objective,status,created_at FROM ad_campaigns WHERE user_id=$1 ORDER BY created_at DESC LIMIT 20",[req.userId]);res.json({enabled:true,campaigns:rows});}catch(e){console.error("advertising/status:",e);res.status(500).json({message:"Erreur serveur."});}});
router.post("/analyze",async(req,res)=>{try{const u=await getUser(req.userId);if(!u||u.plan!=="business")return res.status(403).json({message:"Publicité IA est réservée au plan Business.",code:"business_required"});const {platform,objective,product,audience,budget,duration,zone,creative}=req.body||{};if(!PLATFORMS.includes(platform)||!OBJECTIVES.includes(objective)||!String(product||"").trim())return res.status(400).json({message:"Plateforme, objectif et produit/service sont requis."});if(!process.env.ANTHROPIC_API_KEY)return res.status(500).json({message:"ANTHROPIC_API_KEY n'est pas configurée."});await consumeGeneration(req.userId);const ai=new Anthropic({apiKey:process.env.ANTHROPIC_API_KEY});const system="Tu es un expert senior en publicité digitale pour Facebook, Instagram, TikTok, X/Twitter et WhatsApp, spécialisé dans les marchés africains. Analyse une campagne et propose une stratégie réaliste. Retourne uniquement un JSON valide avec les clés: score, hook, copy, cta, audience, format, budgetRecommendation, durationRecommendation, variants (tableau de 2 objets {hook,angle}), risks (tableau), rationale.";const prompt=`Plateforme: ${platform}\nObjectif: ${objective}\nProduit/service: ${product}\nAudience: ${audience||"à définir"}\nBudget: ${budget||"à définir"}\nDurée: ${duration||"à définir"}\nZone: ${zone||"à définir"}\nCréatif existant: ${creative||"aucun"}`;const m=await ai.messages.create({model:process.env.ANTHROPIC_MODEL||"claude-3-5-haiku-latest",max_tokens:2200,system,messages:[{role:"user",content:prompt}]});const text=(m.content||[]).filter(x=>x.type==="text").map(x=>x.text).join("\n").replace(/```json|```/g,"").trim();let analysis;try{analysis=JSON.parse(text);}catch{analysis={score:0,hook:"",copy:text,cta:"",audience:"",format:"",budgetRecommendation:"",durationRecommendation:"",variants:[],risks:[],rationale:"Réponse IA non structurée."};}res.json({analysis});}catch(e){console.error("advertising/analyze:",e);res.status(e.status||500).json({message:e.message||"Erreur lors de l'analyse publicitaire."});}});
router.post("/approve",async(req,res)=>{try{const u=await getUser(req.userId);if(!u||u.plan!=="business")return res.status(403).json({message:"Publicité IA est réservée au plan Business.",code:"business_required"});const {name="Campagne sans nom",platform,objective,brief,analysis}=req.body||{};if(!PLATFORMS.includes(platform)||!OBJECTIVES.includes(objective)||!analysis)return res.status(400).json({message:"Analyse publicitaire requise avant approbation."});const {rows}=await pool.query("INSERT INTO ad_campaigns(user_id,name,platform,objective,brief,analysis,status) VALUES($1,$2,$3,$4,$5,$6,'approved') RETURNING id,name,platform,objective,status,created_at",[req.userId,name,platform,objective,JSON.stringify(brief||{}),JSON.stringify(analysis)]);res.json({campaign:rows[0],message:"Stratégie approuvée. La campagne est enregistrée et prête pour le connecteur publicitaire de la plateforme."});}catch(e){console.error("advertising/approve:",e);res.status(500).json({message:"Erreur serveur."});}});
module.exports=router;
