const express=require('express'),{requireAuth}=require('../auth'),{pool}=require('../db'),{getUser}=require('../plan');
const {decryptSecret}=require('../lib/secretBox');
const {sendText}=require('../lib/meta');
const router=express.Router();

async function requireBusinessUser(id){
  const u=await getUser(id);
  if(!u) throw Object.assign(new Error('Compte introuvable.'),{status:401});
  if(u.plan!=='business' || (u.plan_expires_at && new Date(u.plan_expires_at)<=new Date())) throw Object.assign(new Error('Cette fonctionnalité est réservée au plan Business.'),{status:403});
  return u;
}
async function getConnection(id){
  const {rows}=await pool.query('SELECT * FROM whatsapp_connections WHERE user_id=$1',[id]);
  return rows[0]||null;
}
async function tokenFor(w){
  if(w?.access_token_enc) return decryptSecret(w.access_token_enc);
  if(w?.access_token) return w.access_token; // legacy BYO rows remain readable during migration
  throw Object.assign(new Error('Connexion WhatsApp incomplète.'),{status:400});
}

router.get('/connection',requireAuth,async(req,res)=>{try{const w=await getConnection(req.userId);if(!w)return res.json({connection:{connected:false}});res.json({connection:{user_id:w.user_id,waba_id:w.waba_id,phone_number_id:w.phone_number_id,display_phone_number:w.display_phone_number,business_name:w.business_name,connection_mode:w.connection_mode||'byo',meta_token_type:w.meta_token_type,meta_status:w.meta_status,ai_enabled:w.ai_enabled,use_catalog:w.use_catalog,take_orders:w.take_orders,answer_pricing:w.answer_pricing,handoff_to_human:w.handoff_to_human,tone:w.tone,greeting_message:w.greeting_message,updated_at:w.updated_at,connected:true}});}catch(e){res.status(500).json({message:'Erreur serveur.'});}});

// Legacy endpoint intentionally disabled for Business centralised onboarding: no client token is accepted.
router.post('/connection',requireAuth,async(req,res)=>res.status(410).json({message:'Cette version utilise la connexion WhatsApp centralisée. Utilisez « Connecter avec Meta ».'}));
router.delete('/connection',requireAuth,async(req,res)=>{try{await pool.query('DELETE FROM whatsapp_connections WHERE user_id=$1',[req.userId]);res.json({ok:true});}catch(e){res.status(500).json({message:'Erreur serveur.'});}});
router.patch('/settings',requireAuth,async(req,res)=>{try{await requireBusinessUser(req.userId);const{rows}=await pool.query(`UPDATE whatsapp_connections SET ai_enabled=COALESCE($1,ai_enabled),use_catalog=COALESCE($2,use_catalog),take_orders=COALESCE($3,take_orders),answer_pricing=COALESCE($4,answer_pricing),handoff_to_human=COALESCE($5,handoff_to_human),tone=COALESCE($6,tone),greeting_message=COALESCE($7,greeting_message),updated_at=NOW() WHERE user_id=$8 RETURNING user_id,waba_id,phone_number_id,display_phone_number,business_name,connection_mode,meta_token_type,meta_status,ai_enabled,use_catalog,take_orders,answer_pricing,handoff_to_human,tone,greeting_message`,[req.body.aiEnabled,req.body.useCatalog,req.body.takeOrders,req.body.answerPricing,req.body.handoffToHuman,req.body.tone,req.body.greetingMessage,req.userId]);if(!rows.length)return res.status(404).json({message:'WhatsApp n’est pas connecté.'});res.json({connection:{...rows[0],connected:true}});}catch(e){res.status(e.status||500).json({message:e.message||'Erreur serveur.'});}});
router.get('/conversations',requireAuth,async(req,res)=>{try{const{rows}=await pool.query(`SELECT c.*,(SELECT json_build_object('text',a.payload->>'text','type',a.type) FROM contact_activities a WHERE a.contact_id=c.id AND a.type IN('message_received','message_sent') ORDER BY a.created_at DESC LIMIT 1) last_message_payload FROM contacts c WHERE c.user_id=$1 AND EXISTS(SELECT 1 FROM contact_activities a WHERE a.contact_id=c.id AND a.type IN('message_received','message_sent')) ORDER BY c.updated_at DESC`,[req.userId]);res.json({conversations:rows});}catch(e){res.status(500).json({message:'Erreur serveur.'});}});
router.post('/conversations/:id/suggest',requireAuth,async(req,res)=>{try{await requireBusinessUser(req.userId);const c=(await pool.query('SELECT * FROM contacts WHERE id=$1 AND user_id=$2',[req.params.id,req.userId])).rows[0];if(!c)return res.status(404).json({message:'Conversation introuvable.'});if(!c.ai_enabled)return res.json({reply:null});if(!process.env.ANTHROPIC_API_KEY)return res.status(500).json({message:'IA non configurée.'});const A=require('@anthropic-ai/sdk'),ai=new A({apiKey:process.env.ANTHROPIC_API_KEY}),h=(await pool.query('SELECT * FROM contact_activities WHERE contact_id=$1 ORDER BY created_at DESC LIMIT 8',[c.id])).rows.reverse().map(a=>`${a.type}: ${a.payload?.text||''}`).join('\n'),m=await ai.messages.create({model:process.env.ANTHROPIC_MODEL||'claude-3-5-haiku-latest',max_tokens:500,system:'Tu es un agent commercial WhatsApp camerounais. Rédige un seul prochain message court, naturel et orienté conversion.',messages:[{role:'user',content:`Contact: ${c.name}\nHistorique:\n${h}`} ]});res.json({reply:(m.content||[]).filter(x=>x.type==='text').map(x=>x.text).join('').trim()});}catch(e){console.error(e);res.status(e.status||500).json({message:e.message||'Erreur serveur.'});}});
router.post('/conversations/:id/send',requireAuth,async(req,res)=>{try{await requireBusinessUser(req.userId);const c=(await pool.query('SELECT * FROM contacts WHERE id=$1 AND user_id=$2',[req.params.id,req.userId])).rows[0],w=await getConnection(req.userId);if(!c)return res.status(404).json({message:'Conversation introuvable.'});if(!w)return res.status(400).json({message:'WhatsApp n’est pas connecté.'});const text=String(req.body?.text||'');if(!text)return res.status(400).json({message:'Message vide.'});const token=await tokenFor(w);if(!(c.window_expires_at&&new Date(c.window_expires_at)>new Date()))return res.status(409).json({message:'La fenêtre WhatsApp de 24 h est expirée. Utilisez un modèle de message approuvé par Meta.'});await sendText(w.phone_number_id,c.phone,text,token);await pool.query("INSERT INTO contact_activities(contact_id,type,payload) VALUES($1,'message_sent',$2)",[c.id,{text,ai_generated:false}]);await pool.query('UPDATE contacts SET last_contacted_at=NOW(),updated_at=NOW() WHERE id=$1',[c.id]);res.json({ok:true});}catch(e){console.error(e);res.status(e.status||500).json({message:e.message||'Erreur serveur.',details:e.details||undefined});}});
module.exports=router;
