const {pool}=require("./db");
const LIMITS={free:Number(process.env.FREE_MONTHLY_QUOTA||15),pro:Number(process.env.PRO_MONTHLY_QUOTA||500),business:Number(process.env.BUSINESS_MONTHLY_QUOTA||2000)};
const periodNow=()=>new Date().toISOString().slice(0,7);
async function ensureUsage(userId){const p=periodNow();await pool.query("INSERT INTO usage_monthly(user_id,period,count) VALUES($1,$2,0) ON CONFLICT(user_id,period) DO NOTHING",[userId,p]);const {rows}=await pool.query("SELECT count FROM usage_monthly WHERE user_id=$1 AND period=$2",[userId,p]);return rows[0]?.count||0;}
async function getUser(id){const {rows}=await pool.query("SELECT * FROM users WHERE id=$1",[id]);return rows[0]||null;}
async function getPlanInfo(user){let plan=user.plan||"free";if(plan!=="free"&&user.plan_expires_at&&new Date(user.plan_expires_at)<=new Date()){await pool.query("UPDATE users SET plan='free',plan_expires_at=NULL WHERE id=$1",[user.id]);plan="free";}const used=await ensureUsage(user.id),quota=LIMITS[plan]||LIMITS.free;return {plan,planExpiresAt:plan==="free"?null:user.plan_expires_at,quota,used,remaining:Math.max(0,quota-used),quotaReached:used>=quota,isAdmin:!!user.is_admin};}
async function summarize(user){const i=await getPlanInfo(user);return {id:user.id,email:user.email,plan:i.plan,planExpiresAt:i.planExpiresAt,quota:i.quota,used:i.used,remaining:i.remaining,quotaReached:i.quotaReached,isAdmin:i.isAdmin,suspended:!!user.suspended};}
async function consumeGeneration(id){const u=await getUser(id);if(!u||u.suspended)throw Object.assign(new Error("Compte indisponible."),{status:403});const i=await getPlanInfo(u);if(i.quotaReached)throw Object.assign(new Error("Quota mensuel atteint. Passez au plan supérieur pour continuer."),{status:402});const p=periodNow();const {rows}=await pool.query("UPDATE usage_monthly SET count=count+1 WHERE user_id=$1 AND period=$2 AND count<$3 RETURNING count",[id,p,i.quota]);if(!rows.length)throw Object.assign(new Error("Quota mensuel atteint."),{status:402});return rows[0].count;}
async function setPlanByEmail(email,plan,days){const e=String(email||"").trim().toLowerCase();if(!e)return null;const expires=plan==="free"?null:new Date(Date.now()+days*86400000);const {rows}=await pool.query("UPDATE users SET plan=$1,plan_expires_at=$2 WHERE lower(email)=lower($3) RETURNING *",[plan,expires,e]);return rows[0]||null;}
module.exports={LIMITS,summarize,getUser,getPlanInfo,consumeGeneration,setPlanByEmail};
